# Generated by Django 3.1.3 on 2022-11-27 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
                ('name', models.CharField(max_length=50)),
                ('paternal_surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentsCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
                ('amount', models.FloatField()),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
